### PR TITLE
Accept AXIOS config

### PR DESCRIPTION
**Pull request by ixje**
An approach to solve https://github.com/CityOfZion/dora/issues/564

From the AXIOS [documentation](https://github.com/axios/axios/blob/master/README.md#request-config)
```
  // `timeout` specifies the number of milliseconds before the request times out.
  // If the request takes longer than `timeout`, the request will be aborted.
  timeout: 1000, // default is `0` (no timeout)
```

### CODE REVIEW

**Comment by ixje** [comment]
So 1 of the test fails because the legacy API is taking too long, which is exactly why we're adding this

**Comment by ixje** [comment]
Perhaps we should support passing a full Axios `RequestConfig` object in which we always override the `baseURL` property to be set to Dora? That would be most future proof

**Comment by ixje** [comment]
Change to accept a `RequestConfig` because that is most future proof. This way people can also configure a proxy if needed

**Comment by lllwvlvwlll** [comment]
This is a great idea! How is the feature exposed to users?  Currently, the methods accept a "network" parameter (`testnet`/`mainnet`).  We could implement a breaking change to accept a configuration object instead.  That could include the network, timeouts, and also api `version`.  Thoughts?

@jplippi  fyi

**Comment by ixje** [comment]
> This is a great idea! How is the feature exposed to users? Currently, the methods accept a "network" parameter (`testnet`/`mainnet`). 

Ah right. I incorrectly assumed we'd import `AXIOS_DORA`. One approach is moving away from static to instance based and then add a constructor to `NeoLegacyREST` and `NeoRest` that accept both a network and optional axios `RequestConfig`. Then also make all `network` arguments on the individual methods optional as a way of temporarily overriding.

So you'd get
```
var legacy = NeoLegacyRest('mainnet', {axios_config});
legacy.addressTXFull("address") // uses mainnet
legacy.addressTXFull("address", network="testnet"); // override default network for just this call
legacy.asset("asset"); // uses mainnet again
```
I don't think adding a `requestConfig` to all methods is what you want to do as developer just because you're running behind a proxy. You want to do that once and forget.

> We could implement a breaking change to accept a configuration object instead. That could include the network, timeouts, and also api `version`. Thoughts?

I'd keep the axios `RequestConfig` and the remaining options separate given that there is already a type for the former. Unless there is a way in typescript that you can tell that the type is a `RequestConfig + other options`, that I don't know.

**Comment by ixje** [comment]
Changes made
- The `NeoRest` and `NeoLegacyREST` classes are renamed to `NeoRESTApi` and `NeoLegacyRESTApi` and are made instance based to allow overriding axios config (for timeout etc) as well as dora url and endpoint urls (to allow pointing it to a self hosted Dora instance). 
   - Added default instantiations with exports to `NeoLegacyREST` and `NeoRest` to enable backwards compatability
- Updated N3 test cases to use T5
- Disabled 2 legacy test cases as they were timing out

**Pull request merged**
